In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris= load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [6]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
X = iris.data

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y= iris.target

In [14]:
from keras.utils import to_categorical

In [16]:
y= to_categorical(y)

In [17]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [18]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler_object = MinMaxScaler()

In [24]:
scaler_object.fit(X_train)

MinMaxScaler()

In [25]:
scaled_X_train = scaler_object.transform(X_train)

In [26]:
scaled_X_test = scaler_object.transform(X_test)

In [39]:
from keras.models import Sequential
from keras.layers import Dense

In [46]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [48]:
model.fit(scaled_X_train, y_train,epochs=150,verbose=0)

In [49]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 8)                 40        
                                                                 
 dense_19 (Dense)            (None, 8)                 72        
                                                                 
 dense_20 (Dense)            (None, 3)                 27        
                                                                 
Total params: 139 (556.00 Byte)
Trainable params: 139 (556.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [51]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 10ms/step


array([[4.7302521e-03, 9.5738888e-01, 3.7880886e-02],
       [9.9133486e-01, 8.6652143e-03, 4.4036824e-08],
       [2.8683583e-06, 1.6377816e-02, 9.8361939e-01],
       [3.2741241e-03, 8.4362900e-01, 1.5309685e-01],
       [1.8398307e-03, 7.6854706e-01, 2.2961308e-01],
       [9.8221314e-01, 1.7786445e-02, 4.1624153e-07],
       [1.0004794e-02, 9.7165155e-01, 1.8343704e-02],
       [1.6469650e-05, 2.9016446e-02, 9.7096711e-01],
       [9.3964027e-04, 2.4055701e-01, 7.5850332e-01],
       [8.8665225e-03, 9.6380687e-01, 2.7326602e-02],
       [2.0435084e-04, 1.9646767e-01, 8.0332798e-01],
       [9.9660146e-01, 3.3985155e-03, 5.5538582e-08],
       [9.9499595e-01, 5.0040418e-03, 3.8862634e-08],
       [9.9670464e-01, 3.2953653e-03, 4.1545594e-08],
       [9.9748117e-01, 2.5188774e-03, 9.3330979e-09],
       [2.1458450e-03, 8.9707148e-01, 1.0078266e-01],
       [1.7548498e-05, 2.9651914e-02, 9.7033048e-01],
       [1.1758716e-02, 9.6331161e-01, 2.4929656e-02],
       [5.7761013e-03, 9.454

In [56]:
model.predict(scaled_X_test).argmax(axis=1)

2/2 [==============================] - 0s 9ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [57]:
[1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2] == [1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2]

False

In [58]:
model.metrics_names

['loss', 'accuracy']

In [59]:
model.evaluate(x= scaled_X_test,y= y_test)

2/2 [==============================] - 1s 13ms/step - loss: 0.1164 - accuracy: 0.9600


[0.1164025291800499, 0.9599999785423279]

In [62]:
predictions= model.predict(scaled_X_test).argmax(axis=1)

2/2 [==============================] - 0s 7ms/step


In [75]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [63]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [67]:
print(confusion_matrix(predictions,y_test.argmax(axis=1)))

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]


In [68]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [69]:
print(classification_report(predictions,y_test.argmax(axis=1)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [70]:
model.save("myfirstmodel.h5")

C:\Users\te20312262\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [71]:
from keras.models import load_model

In [72]:
new_model = load_model("myfirstmodel.h5")

In [77]:
check = new_model.predict(scaled_X_test).argmax(axis=1)

2/2 [==============================] - 0s 9ms/step


In [78]:
accuracy_score(check,y_test.argmax(axis=1))

0.96